const testQuestions: string[] = [
  'I am comfortable spending $20 for a meal',
  'I drink bubble tea as and when I like',
  'I prefer ordering food on Grab than going out to dabao',
  'I usually buy a drink with my meal when I eat out',
  'I always give in to my food cravings',
  'I pay attention to having a balanced diet',
  'I’ve travelled overseas beyond South East Asia',
  'I usually go overseas during school holidays',
  'I’ve travelled to all the continents before',
  'I have clothes for winter weather',
  'I had to replace my passport not because it expired',
  'I didn’t know there’s a blue CHAS card',
  'What’s a CHAS card',
  'I only see my family doctor',
  'My parents got me braces',
  'I discard unused medicine once I’ve recovered',
  'I go straight to the doctor when I’m sick',
  'I had tuition growing up',
  'My parents were at every parent teacher meeting',
  'I had musical instrument lessons when I was younger',
  'I had my first phone in primary school',
  'My parents usually drive me to school',
  'My school shoes were not from Bata',
  'E-learning was not a problem for me',
  'I went to a private kindergarten',
  'There was no question about going to university',
  'I have my own bedroom',
  'I have an Apple Pencil',
  'I have an Apple Watch',
  'Sometimes I put my airpods on just so people don’t talk to me',
  'I have an embroidered Kanken bag',
  'I have custom sneakers',
  'I have a gym membership',
  'I am older than 18 and still get a monthly allowance from my parents',
  'I have/had a domestic helper',
  'I have/had a Switch',
  'I have/had a Xbox/Playstation/Wii',
  'I have a driver’s license',
  'I know I have the option of studying overseas if I cannot score well',
  'I just take a grab/taxi if i’m late for something',
  'I don’t wait for sales to buy things',
  'I watched Disney Channel growing up',
  'I have never worked in my life',
  'My family has a car',
  'I don’t live in a HDB',
  'My family usually goes to private hospitals',
  'My family has more than one car',
  'I never fly budget',
  'I’ve stayed in a five star hotel',
  'I have a Netflix or Spotify subscription',
  'I have my own laptop/desktop',
  'I have more than 10 pairs of shoes',
  'At least one of my parents are university graduates',
  'I have my own bed',
  'My bed is queen sized or bigger',
  'I’m not on any form of financial aid',
  'I thrift because it’s trendy and/or environmentally friendly',
  'I have a branded windbreaker',
  'I have gotten/will get lasik',
  'My bedroom has air-conditioning',
  'I sometimes paint my own walls',
  'I have seen one of the seven wonders of the world',
  'I’ve gone skiing/snowboarding',
  'I’ve been to a live concert',
  'I eat Acai bowls',
  'I regularly get my hair done',
  'I’ve eaten at PS Cafe',
  'I regularly buy Evian/Smartwater water',
  'I have new clothes for festive holidays every year',
  'I own a formal outfit (Suit/Formal Dress)',
  'I have given/received a bouquet of flowers',
  'I’ve celebrated my birthday at a hotel',
  'I’ve eaten at Haidilao at least twice',
  'I think that my airpods pro were worth the price',
  'I have Calvin Klein underwear',
  'I have a non-disposable film camera',
  'I have Gucci slides',
  'I have something from FILA',
  'I have Air Force Ones',
  'I have a Mirrorless camera',
  'I have Yeezys',
  'I know how to load the dishwasher',
  'I have a bathtub',
  'I have went to a kpop fanmeet',
  'Hi I’m from OCS',
  'I have a figurine/model collection',
  'I have something from ADLV',
  'I play golf',
  'I have a country club membership',
  'I have lululemon stuff',
  'I go bouldering',
  'I invest in stocks',
  'I have a husky',
  'I have had my acne treated professionally',
  'I can’t find some of my Faber Castell colour pencils',
  'I have/had a daily planner that I maintained',
  'I don’t mind travelling far for a cute place',
  'I went to an international school',
  'I have never hung at a HDB void deck',
  'I just buy new things instead of fixing old ones',
]

export default testQuestions
