const testQuestions: string[] = [   
  'I am comfortable spending $20 for a meal',
  'I am willing to spend more than $5 for a drink alone',
  'I prefer ordering food on Grab than going out to dabao',
  'I usually buy a drink with my meal when I eat out',
  'I always give in to my food cravings',
  'I pay attention to having a balanced diet',
  'I’ve travelled overseas beyond South East Asia',
  'I usually go overseas during school holidays',
  'I’ve travelled to at least 2 continents',
  'I have clothes for winter weather',
  'I had to replace my passport not because it expired',
  'I don’t have a blue CHAS Card',
  'I don’t usually go to polyclinics',
  'My parents got me braces',
  'I go straight to the doctor when I’m sick',
  'I had tuition growing up',
  'My parents were at every parent teacher meeting',
  'I attended enrichment classes when I was younger',
  'I had musical instrument lessons when I was younger',
  'I had my first phone in primary school',
  'My parents usually drive me to school',
  'I replaced my school shoes once they were damaged',
  'E-learning was not a problem for me',
  'I went to a private kindergarten',
  'There was no question about going to university',
  'I have my own bedroom',
  'I have an iPhone',
  'I have an Apple Pencil',
  'I have a Herschel/Kanken bag',
  'I have trendy sneakers',
  'I have a gym membership',
  'I am older than 19 and still get a monthly allowance from my parents',
  'I have/had a domestic helper',
  'I have/had a gaming console',
  'I have a driver’s license',
  'I know I have the option of studying overseas if I cannot score well', 
  'I just take a grab/taxi if i’m late for something',
  'I don’t wait for sales to buy things',
  'I watched Disney Channel growing up', 
  'Never have I had to work for pocket money',
  'My family has a car', 
  'I don’t live in a HDB',
  'My family usually goes to private hospitals', 
  'My family has more than one car',
  'I never fly budget', 
  'I’ve stayed in a five star hotel', 
  'I have a Netflix or Spotify subscription', 
  'I have my own laptop/desktop',
  'I have more than 10 pairs of shoes', 
  'At least one of my parents are university graduates', 
  'I have my own bed', 
  'My bed is queen sized or bigger', 
  'I’m not on any form of financial aid', 
  'I thrift because it’s trendy and/or environmentally friendly', 
  'I have a branded windbreaker', 
  'I have gotten/will get lasik',
  'My bedroom has air-conditioning', 
  'I like to decorate my room walls',
  'I have seen one of the seven wonders of the world', 
  'I’ve gone skiing/snowboarding', 
  'I’ve been to a live concert by a band/artist that I follow',
  'I regularly eat Acai bowls', 
  'I regularly get my hair done', 
  'I’ve eaten at PS Cafe', 
  'I regularly buy bottled water', 
  'I have new clothes for festive holidays every year', 
  'I own a formal outfit (Suit/Formal Dress)', 
  'My gifts for my friends are never below $50',
  'I’ve celebrated my birthday at a hotel', 
  'I have branded underwear',
  'I have a non-disposable film camera', 
  'I have branded slides', 
  'I have something from Patagonia',
  'I have a Mirrorless camera', 
  'I have a bathtub', 
  'I have been to F1 events',
  'Hi i’m from OCS', 
  'I have a figurine/model collection', 
  'My family eats out regularly',
  'I have a country club membership', 
  'I have multiple sets of workout tights',
  'I go bouldering', 
  'I invest in stocks', 
  'I have/had a pet',
  'I have had my acne treated professionally',
  'I’ve gone for Halloween Horror Nights',
  'I have/had a daily planner that I maintained', 
  'I don’t mind travelling far for a nice place', 
  'I went to an international school', 
  'I have never hung at a HDB void deck', 
  'I just buy new things instead of fixing old ones',
  'I always get the latest phone model',
  'I throw away torn/overstretched underwear',
  'I’m on a car more than I’m on public transport',
  'I have cards from different banks',
  'I don’t usually keep track of my spending',
  'I tend to study at cafes',
  'I have/had a Universal Studios pass',
  'My parents are paying/paid for my university fees while I was studying',
  'My family has a fibre TV subscription',
]

export default testQuestions

