---
- name: fetch credentials into dot env files
  shell: |
    # fetch database secret from aws secrets manager
    ReadyAnotPg=$(aws secretsmanager get-secret-value --secret-id prod/ReadyAnot/PostgreSQL | jq -r ".SecretString")
    
    # parse and format response
    username=$(jq ".username" <<< $ReadyAnotPg | tr -d \")
    password=$(jq ".password" <<< $ReadyAnotPg | tr -d \")
    host=$(jq ".host" <<< $ReadyAnotPg | tr -d \")
    port=$(jq ".port" <<< $ReadyAnotPg | tr -d \")
    
    # Remove existing dotenv file
    rm -rf {{ home_dir }}/.env
    
    # Generates .env
    echo DATABASE_URL=\"postgresql://$username:$password@$host:$port/readyanot-dev?schema=public\" >> {{ home_dir }}/.env
    echo HOSTNAME=\"http://localhost:3000\" >> {{ home_dir }}/.env
  args:
    executable: /bin/bash
