name: Build and Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.x
      
      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2.2.0
        with:
          playbook: ansible/main.yml
